### PR TITLE
Loading animation added  Made Responsive the Extension and Ui changed 

### PR DESCRIPTION
**Pull request by Shyam3050**
Before

Screenshot (34)

After

Screenshot (33)

This is mobile Responsive also
Screenshot (35)
Screenshot (36)

### CODE REVIEW

**Comment by Shyam3050** [comment]
currently have 50px
how much space can reduce

**Comment by Shyam3050** [comment]
Screenshot (37)

**Comment by Shyam3050** [comment]
Screenshot (42)
Screenshot (41)

**Comment by Shyam3050** [comment]
> @Shyam3050 issue no?
> 
> Also, reduce the space between the logo and the box

issue no is #18

**Review by Susmita-Dey — APPROVED** [review]
Great job

**Pull request merged**
