### PR TITLE
task: worked on fear page

### PR DESCRIPTION
**Pull request by akebu6**
kept the pages the same way as the rest (fear and sad), just worked on the text. 
Also fixed a typo on the anxious.html page

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
Ss please

**Comment by akebu6** [comment]
Here is the screenshot for the fear page

Screenshot 2023-01-28 at 5 26 45 PM

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Align the items in center

**Comment by akebu6** [comment]
> Align the items in center

The text is already aligned, it's just in the screenshot the browser was minimised. It's the same for the pages when I view them in a minimised window. So there are no changes I can make. Try to view the changes in a large window

**Pull request merged**
