### PR TITLE
task: worked on angry page

### PR DESCRIPTION
**Pull request by akebu6**
worked on the angry page, since it's slightly similar to being angry, I decided to just change the text but kept it almost similar. Hope that is still okay. Let me know what you would want changed and removed

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
ss please

**Comment by akebu6** [comment]
This is the screenshot for the angry page

Screenshot 2023-01-28 at 5 24 13 PM

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Align items in center.

**Comment by akebu6** [comment]
> Align items in center.

The text is already aligned, it's just in the screenshot the browser was minimised. It's the same for the pages when I view them in a minimised window. So there are no changes I can make. Try to view the changes in a large window

**Pull request merged**
